#!/usr/bin/env python

import sys
import re

supported_kw = [
    'feat',
    'fix',
    'revert',
    'refactor',
    'build',
    'ci',
    'doc',
    'style',
    'test'
]

requiredRegex = '(' + '|'.join(supported_kw) + '):.*'

commitMessageFile = open(sys.argv[1]) #The first argument is the file
commitMessage = commitMessageFile.read().strip()

if re.search(requiredRegex, commitMessage) is None:
    print(f"Commit message is not well formatted (must start with one of the keywords: {', '.join(supported_kw)}).")
    sys.exit(1)

sys.exit(0)
